author: Jürgen Mülbert
author_url: http://jmuelbert.github.io/jmbde-macos/
github_url: https://github.com/jmuelbert/jmbde-macos
root_url: http://jmuelbert.github.io/jmbde-macos/
module: jmbde
output: docs
theme: fullwidth
xcodebuild_arguments: [-workspace, 'jmbde.xcworkspace', -scheme, 'jmbde']
