os: osx
osx_image: xcode10.2
language: objective-c
cache: cocoapods

xcode_workspace: jmbde.xcworkspace
xcode_scheme: jmbde-macos

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - WORKSPACE=jmbde.xcworkspace
    - PROJECT=jmbde.xcodeproj
    - OSX_FRAMEWORK_SCHEME=jmbde-macos
    - OSX_SDK=macosx10.14          
    - SWIFT_VERSION=4.2.1
    - UPDATE_DOCS=true
    - EXPANDED_CODE_SIGN_IDENTITY="-"
    - EXPANDED_CODE_SIGN_IDENTITY_NAME="-"
    - CODE_SIGN_IDENTITY=""
    - CODE_SIGNING_REQUIRED=NO
    - DESTINATION="arch=x86_64"
    - SCHEME="$OSX_FRAMEWORK_SCHEME"
    - SDK="$OSX_SDK"

before_install:
  - 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
  - brew update
  - brew outdated xctool || brew upgrade xctool
  - brew outdated carthage || brew upgrade carthage

install:
  - gem install bundler --no-document
  - bundle install
  - pod install || pod install --repo-update
  - git remote set-url origin "https://${GITHUB_TOKEN}@github.com/jmuelbert/jmbde-macos.git"

before_script:
  - pod install --repo-update
  - xcodebuild -version
  - xcodebuild -showsdks
  - swift --version
  - carthage version
  - swiftlint version

script:
  - set -o pipefail
  # Build Framework in Debug and Run Tests if specified
  - echo "Build without tests"
  - xcodebuild build 
    -workspace "$WORKSPACE" 
    -scheme "$SCHEME" 
    -sdk "$SDK" 
    -destination "$DESTINATION" 
    -configuration Debug 
    ONLY_ACTIVE_ARCH=NO 
    ENABLE_TESTABILITY=YES 
    CODE_SIGN_IDENTITY=""
    CODE_SIGNING_REQUIRED=NO | xcpretty -c;

after_success:
  - danger
  - jazzy
  - rubocop
  - swiftlint lint
  - slather
  - bash <(curl -s https://codecov.io/bash) -J JMBde
  - test $TRAVIS_PULL_REQUEST == "false" &&
    test $TRAVIS_BRANCH == "master" &&
    test $UPDATE_DOCS == "true" &&
    .scripts/update-gh-pages

#deploy:
#  - provider: script
#    # script: bash .scripts/update-gh-pages.sh
#    skip_cleanup: true
#    on:
#        all_branches: true
#        condition: '"$TRAVIS_BRANCH" == "master" || "$TRAVIS_TAG" != ""'
