language: objective-c
osx_image: xcode9.4

branches:
  only: master
script: placeholder # workaround for https://github.com/travis-ci/travis-ci/issues/4681  

notifications:
  email: false

before_install:
- gem install bundler
- bundle install
- bundle exec pod repo update --silent
- brew update
- brew outdated xctool || brew upgrade xctool
- brew outdated carthage || brew upgrade carthage
- git remote set-url origin "https://${GITHUB_TOKEN}@github.com/jmuelbert/jmbde-macos.git"
script:
- set -o pipefail
- swift --version
- xcodebuild clean build
- swiftlint lint
- bundle exec danger --verbose
- bundle exec fastlane travis
  - bash <(curl -s https://codecov.io/bash)