language: swift
osx_image: xcode10.1
xcode_project: jmbde.workspace
xcode_scheme: jmbde
xcode_destination: platform=macOS

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - WORKSPACE=jmbde.xcworkspace
    - PROJECT=jmbde.xcodeproj
    - OSX_FRAME_WORK_SCHEME="jmbde-macos"
    - OSX_SDK="macosx10.14"          
    - SWIFT_VERSION="4.2.1"
    - UPDATE_DOCS="true"
    - EXPANDED_CODE_SIGN_IDENTITY="-"
    - EXPANDED_CODE_SIGN_IDENTITY_NAME="-"

branches:
  execpt:
    - gh-pages

before_install:
  - 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'

install:
  - gem install bundler
  - bundle install
  - brew update
  - brew outdated xctool || brew upgrade xctool
  - brew outdated carthage || brew upgrade carthage
  - git remote set-url origin "https://${GITHUB_TOKEN}@github.com/jmuelbert/jmbde-macos.git"


matrix:
  - DESTINATION="arch=x86_64"                    SCHEME="$OSX_FRAMEWORK_SCHEME"     SDK="$OSX_SDK"     RUN_TESTS="YES" POD_LINT="NO"
notifications:
  email: false

before_script:
  - pod install
  - bundle exec pod repo update --silent

script:
  - set -o pipefail
  - xcodebuild -version
  - swift --version
  - xcodebuild -showsdks

  # Build Framework in Debug and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty -c;
    else
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
    fi

  # Run `pod lib lint` if specified
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint --quick;
    fi

after_success:
  - danger
  - slather
  - jazzy
  - swiftlint lint
  - bash <(curl -s https://codecov.io/bash) -J JMBde
  - test $TRAVIS_PULL_REQUEST == "false" &&
    test $TRAVIS_BRANCH == "master" &&
    test $UPDATE_DOCS == "true" &&
    .scripts/update-gh-pages

jobs:
  include:
    - script: # pod lib lint --verbose --allow-warnings
    - stage: deploy
      before_deploy: carthage build --no-skip-current && carthage archive jmbde
      deploy:
        - provider: releases
          api_key:
            secure: 
          file:
            - jmbde.framework.zip
          skip_cleanup: true
          overwrite: true
          on:
            repo: jmuelbert/jmbde-macos
            tags: true
        - provider: script
          script: pod trunk push
          on:
            tags: true    