language: swift
osx_image: xcode10
xcode_project: JMBde.workspace
xcode_scheme: JMBde
xcode_destination: platform=macOS

branches:
  execpt:
    - gh-pages

before_install:
- gem install bundler
- bundle install
- bundle exec pod repo update --silent
- brew update
- brew outdated xctool || brew upgrade xctool
- brew outdated carthage || brew upgrade carthage
- git remote set-url origin "https://${GITHUB_TOKEN}@github.com/jmuelbert/jmbde-macos.git"

install:
  - gem install xcpretty

env:
  global:
   global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - FRAMEWORK_NAME="JMBde"
    - UPDATE_DOCS="true"

matrix:
  include:
    - osx_image: xcode10.1
      env: SCHEME="macOS"  SDK="macosx10.13"          DESTINATION="arch=x86_64"                    SWIFT_VERSION="4.2!

notifications:
  email: false



script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild
    -project "$FRAMEWORK_NAME.xcodeproj"
    -scheme "$FRAMEWORK_NAME-$SCHEME"
    -sdk "$SDK"
    -destination "$DESTINATION"
    -configuration Debug
    ONLY_ACTIVE_ARCH=YES
    GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES
    GCC_GENERATE_TEST_COVERAGE_FILES=YES
    SWIFT_VERSION=$SWIFT_VERSION
    test

after_success:
- swift --version
- swiftlint lint
 - bash <(curl -s https://codecov.io/bash) -J JMBde
  - test $TRAVIS_PULL_REQUEST == "false" &&
    test $TRAVIS_BRANCH == "master" &&
    test $UPDATE_DOCS == "true" &&
    .scripts/update-gh-pages