os: osx
osx_image: xcode10.1
language: objective-c
cache: cocoapods
install: pod install || pod install --repo-update

xcode_workspace: jmbde.xcworkspace
xcode_scheme: jmbde

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - WORKSPACE=jmbde.xcworkspace
    - PROJECT=jmbde.xcodeproj
    - OSX_FRAMEWORK_SCHEME=jmbde-macos
    - OSX_SDK=macosx10.14          
    - SWIFT_VERSION=4.2.1
    - UPDATE_DOCS=true
    - EXPANDED_CODE_SIGN_IDENTITY="-"
    - EXPANDED_CODE_SIGN_IDENTITY_NAME="-"
    - CODE_SIGN_IDENTITY=""
    - CODE_SIGNING_REQUIRED=NO
    - DESTINATION="arch=x86_64"
    - SCHEME="$OSX_FRAMEWORK_SCHEME"
    - SDK="$OSX_SDK"

script:
  - set -o pipefail
  # Build Framework in Debug and Run Tests if specified
  - echo "Build without tests"
  - xcodebuild build 
    -workspace "$WORKSPACE" 
    -scheme "$SCHEME" 
    -sdk "$SDK" 
    -destination "$DESTINATION" 
    -configuration Debug 
    ONLY_ACTIVE_ARCH=NO 
    ENABLE_TESTABILITY=YES 
    CODE_SIGN_IDENTITY=""
    CODE_SIGNING_REQUIRED=NO | xcpretty -c;


deploy:
  - provider: script
    # script: bash .scripts/update-gh-pages.sh
    skip_cleanup: true
    on:
        all_branches: true
        condition: '"$TRAVIS_BRANCH" == "master" || "$TRAVIS_TAG" != ""'